### ISSUE TITLE
How can I get boardreader API key?

### ISSUE THREAD

**Issue by strategist922** [aaron2012r2/BoardReader-Shiny-App#1]
Hi,
  May I know I\ho can I get the Boardreader API key so that I can try this shiny App?

Thanks and best regards,
James Chang

**Comment by aaron2012r2** [comment]
Hi James,
The reason I created a field for the API Key is because it's a paid service. The official websites are: http://boardreader.com/ and http://api.boardreader.com/
If you're able to contact them, you can purchase an API key for use.
